@extends('layouts.app')

@section('title', 'Reports')
@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-primary">Dashboard</a>
    <span class="mx-1">/</span>
    <span class="font-medium text-primary">Reports</span>
@endsection

@section('content')
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-6 gap-3">
        <div>
            <h1 class="text-2xl font-bold text-primary">Reports</h1>
            <p class="text-slate-500 text-sm">View and generate platform reports.</p>
        </div>
    </div>

    {{-- Generate Report Form --}}
    <div class="bg-white rounded-card shadow-sm border border-slate-100 p-6 mb-8">
        <h2 class="font-semibold text-primary mb-4">Generate New Report</h2>
        <form action="{{ route('admin.reports.generate') }}" method="POST" class="flex flex-col sm:flex-row gap-3 items-end">
            @csrf
            <div class="flex-1 w-full">
                <label for="type" class="block text-sm font-medium text-slate-700 mb-1">Type</label>
                <select name="type" id="type" required
                    class="w-full rounded-btn border-slate-200 bg-slate-50 text-sm focus:ring-2 focus:ring-secondary focus:border-secondary">
                    <option value="">Select type...</option>
                    @foreach(['student' => 'Students', 'instructor' => 'Instructors', 'course' => 'Courses', 'assignment' => 'Assignments', 'support' => 'Support Tickets', 'system' => 'System Summary'] as $value => $label)
                        <option value="{{ $value }}" @selected(old('type') === $value)>{{ $label }}</option>
                    @endforeach
                </select>
                @error('type')
                    <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                @enderror
            </div>
            <div class="w-full sm:w-40">
                <label for="format" class="block text-sm font-medium text-slate-700 mb-1">Format</label>
                <select name="format" id="format" required
                    class="w-full rounded-btn border-slate-200 bg-slate-50 text-sm focus:ring-2 focus:ring-secondary focus:border-secondary">
                    <option value="pdf" @selected(old('format') === 'pdf')>PDF</option>
                    <option value="excel" @selected(old('format') === 'excel')>Excel</option>
                </select>
                @error('format')
                    <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                @enderror
            </div>
            <div class="flex-1 w-full">
                <label for="title" class="block text-sm font-medium text-slate-700 mb-1">Title</label>
                <input type="text" name="title" id="title" required placeholder="Report title..."
                    class="w-full rounded-btn border-slate-200 bg-slate-50 text-sm focus:ring-2 focus:ring-secondary focus:border-secondary">
                @error('title')
                    <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                @enderror
            </div>
            <button type="submit"
                class="px-6 py-2 rounded-btn bg-primary text-white text-sm font-medium hover:bg-primary-700 transition whitespace-nowrap">
                Generate
            </button>
        </form>
    </div>

    {{-- Reports Table --}}
    <div class="bg-white rounded-card shadow-sm border border-slate-100 overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead>
                    <tr class="border-b border-slate-100 bg-slate-50/60">
                        <th class="text-left px-6 py-3 font-semibold text-slate-600">Type</th>
                        <th class="text-left px-6 py-3 font-semibold text-slate-600">Title</th>
                        <th class="text-left px-6 py-3 font-semibold text-slate-600">Format</th>
                        <th class="text-left px-6 py-3 font-semibold text-slate-600">Generated By</th>
                        <th class="text-left px-6 py-3 font-semibold text-slate-600">Date</th>
                        <th class="text-right px-6 py-3 font-semibold text-slate-600">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100">
                    @forelse($reports as $report)
                        <tr class="hover:bg-slate-50/50 transition">
                            <td class="px-6 py-4">
                                <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-secondary/10 text-secondary capitalize">
                                    {{ $report->type }}
                                </span>
                            </td>
                            <td class="px-6 py-4 font-medium text-slate-800">{{ $report->title }}</td>
                            <td class="px-6 py-4 text-slate-500 uppercase text-xs font-semibold">{{ $report->format ?? '—' }}</td>
                            <td class="px-6 py-4 text-slate-500">{{ $report->generator->name ?? '—' }}</td>
                            <td class="px-6 py-4 text-slate-400">{{ $report->created_at->format('M d, Y H:i') }}</td>
                            <td class="px-6 py-4 text-right">
                                @if($report->file_path)
                                    <a href="{{ route('admin.reports.download', $report) }}"
                                        class="inline-flex items-center gap-1 px-3 py-1.5 rounded-btn bg-secondary/10 text-secondary text-xs font-medium hover:bg-secondary/20 transition">
                                        <div class="w-3.5 h-3.5">
                                            @include('layouts.nav.icon', ['name' => 'download'])
                                        </div>
                                        Download
                                    </a>
                                @else
                                    <span class="text-slate-300 text-xs">No file</span>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6">
                                <x-empty-state title="No reports yet" message="Generated reports will appear here." icon="chart" />
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection
